### ISSUE TITLE
MS Thesis Review

### ISSUE THREAD

**Issue by gwenchee** [gwenchee/ms-thesis#20]
This issue can be closed after @katyhuff gives her final comments on this thesis: 
[gwen-ms-thesis-11-30.pdf](https://github.com/gwenchee/ms-thesis/files/3907834/gwen-ms-thesis-11-30.pdf)

This thesis fixes all the comments in #19. 

Sorry this took so long, there was a lot to fix. Should I still expect to send my thesis to Professor Stubbins and Uddin on Monday?

**Comment by katyhuff** [comment]
Please tighten up the abstract and conclusion in particular to emphasize, in formal language, what was accomplished. Throughout: stop using "we" so much (frequently, it is avoidable if 'This work" or "this thesis" is treated as the subject of the sentence).

In both the abstract and the conclusion:
- structure the flow more clearly (gap, method, accomplishment)
- more concise phrasing
- avoid "we" and "our" in order to be clearer about what this thesis accomplished independent of the work of a larger group. For example, instead of "In this work, our first goal is to model", say "This work models"
- Similarly, there is confusion in the abstract about who "we" is. In some places it is the imperial we (you, who did the work) while in adjacent places, "we" and "our" refers to the united states.
- use consistent tense (in some places you use past, in the final sentence you use present tense. Things that have already been done are in the past, so use past tense for those.)
- Rather than "we recommend" be quantitative and precise: "The results demonstrated that time can be saved if ... ".


The conclusion chapter :
- Has only one subsection. Subsections are used to separate text into parts. Either add a subsection heading at the same level as 6.1 to capture the discussion of results in the first, unsectioned portion, or delete the future work subsection heading and allow it to be part of the rest of the chapter text.
- In the future work section, don't refer to "we" unless you plan to do the work.

When the conclusion and abstract have been tightened up (imagine Profs. Stubbins and Uddin will only read these two sections), you may send it to them.

**Comment by gwenchee** [comment]
I tightened my abstract and conclusion, and mailed it to Professor Stubbins and Uddin.
